### PR TITLE
Update splashscreen.cpp. Improve color contrast on InitMessage QColor from 55 to 255.

### PR DESCRIPTION
**Pull request by Overdrive5**
Improve color contrast on InitMessage for easier readability. Line 194.

### CODE REVIEW

**Comment by Overdrive5** [comment]
SugarSplash1

**Comment by decryp2kanon** [comment]
good to know, but still no idea why we should change the color?

**Comment by Overdrive5** [comment]
The original color is pretty hard to see. Maybe will give a new user a clue what's going on when starting it up? Just a thought.
SugarSplash

**Comment by decryp2kanon** [comment]
oh i understood.

**Review by decryp2kanon — APPROVED** [review]

**Pull request merged**
