### PR TITLE
add: disable debug.log as an option

### LINKED ISSUE #104: reduce filesize debug.log
[Forwarded from Raku Ten]
I suggest when running wallet to add parameters to keep the debug.log, a lot of people don't need it

[Forwarded from Volbil]
I guess we can set it to False

[Forwarded from Volbil]
And add flag which will enable it

`util.cpp`
image

following options
- reduce size significantly
  * mostly `UpdateTip: new best=`
- disable debug.log by default
  * make an option for devs to debug
- `-shrinkdebugfile` as default

### PR DESCRIPTION
**Pull request by decryp2kanon**
debug: 
`watch -n5 ls -lh debug.log`

### CODE REVIEW

**Comment by decryp2kanon** [comment]
still getting debug file as `0`
seems failed

**Comment by decryp2kanon** [comment]
seems working
1. default: no any debug
2. `-enabledebuglogfile`: write `debug.log`
3. `-printtoconsole`: same as before

**Comment by cryptozeny** [comment]
rplant suggested:
default as same as before,
but add disable logging option.

**Comment by decryp2kanon** [comment]
however no debug file didn't improve the speed when `reindex-chainstate`
image

**Comment by decryp2kanon** [comment]
i made something mistook. closing.

**Pull request closed without merging**
