### PR TITLE
[WIP2] option: -fastsync: Never check PoW during IBD

### PR DESCRIPTION
**Pull request by decryp2kanon**
i am not sure, if this is good. however just testing case. in case ARM, sync seems too slow, due to lack of Yespower support.

- RAM usage is almost same
image

- CPU usage much less
image

### CODE REVIEW

**Comment by decryp2kanon** [comment]
image

3GB swap is better on 1cpu1024ram VPS

**Comment by decryp2kanon** [comment]
image
image

-fastsync tends to use more traffic

**Comment by decryp2kanon** [comment]
image

fastsync seems faster. however benchmark was wrong.

**Review by cryptozeny — CHANGES_REQUESTED** [review]
NACK
do not merge yet! need more testing

**Pull request closed without merging**
