### PR TITLE
[WIP] Sugarchain: add: synctime by okoto

### PR DESCRIPTION
**Pull request by cryptozeny**
https://gist.github.com/okoto-xyz/c8eead8d7eb8ffc01310abda267bec93

### CODE REVIEW

**Comment by cryptozeny** [comment]
```
$ ./synctime.py 
from: can't read /var/mail/datetime
from: can't read /var/mail/datetime
./synctime.py: line 5: logFilePath: command not found
./synctime.py: line 6: outputFilePath: command not found
./synctime.py: line 8: syntax error near unexpected token `('
./synctime.py: line 8: `with open(logFilePath, "r") as logFile, open(outputFilePath, "w") as csvFile:'
```

**Review by okoto-xyz — COMMENTED** [review]
good

**Comment by cryptozeny** [comment]
IBD `3x` faster
image

**Comment by cryptozeny** [comment]
reindex `2.4x` faster
image

**Comment by cryptozeny** [comment]
moved to https://github.com/sugarchain-project/synctime

closing

**Pull request closed without merging**
